import {
	Laptop,
	ShoppingBag,
	ConciergeBell,
	ArrowRightLeft,
	Moon,
	SunMedium,
	Circle,
	DollarSign,
	Home,
	Users,
	Plus,
	Contact,
	Pen,
	Trash,
	MoreHorizontal,
	DoorOpen,
	Store,
	Tag,
	X,
	MenuSquare,
} from "lucide-react";
import { TbArrowRight, TbBrandGoogle, TbChevronLeft, TbDelta, TbLoader } from "react-icons/tb";

export const Icons = {
	spinner: TbLoader,
	google: TbBrandGoogle,
	sun: SunMedium,
	moon: Moon,
	close: X,
	laptop: Laptop,
	moreHorizontal: MoreHorizontal,
	plus: Plus,
	logo: TbDelta,
	bell: ConciergeBell,
	trash: Trash,
	pen: Pen,
	circle: Circle,
	dollar: DollarSign,
	home: Home,
	persons: Users,
	store: Store,
	employee: Contact,
	tag: Tag,
	doorOpen: DoorOpen,
	transaction: ArrowRightLeft,
	menu: MenuSquare,
	chevronLeft: TbChevronLeft,
	shoppigBag: ShoppingBag,
	arrowRight: TbArrowRight,
};
